default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: njordr
  username: postgres
  password: postgres
  host: localhost
  port: 5432
test:
  <<: *default
  database: njordr
production:
  <<: *default
  database: njordr
  username: postgres
  password: postgres
